/* 
 * File:   pl_hawat_jUVCamera_UVCWebCam.h
 * Author: hawat
 *
 * Created on 19 lipiec 2012, 01:03
 */
#include <jni.h>

#ifndef PL_HAWAT_JUVCAMERA_UVCWEBCAM_H
#define	PL_HAWAT_JUVCAMERA_UVCWEBCAM_H

#ifdef	__cplusplus
extern "C" {
#endif
/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class pl_hawat_jUVCamera_UVCWebCam */


/*
 * Class:     pl_hawat_jUVCamera_UVCWebCam
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pl_hawat_jUVCamera_UVCWebCam_stop
  (JNIEnv *, jobject);

/*
 * Class:     pl_hawat_jUVCamera_UVCWebCam
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pl_hawat_jUVCamera_UVCWebCam_start
  (JNIEnv *, jobject);

/*
 * Class:     pl_hawat_jUVCamera_UVCWebCam
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pl_hawat_jUVCamera_UVCWebCam_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     pl_hawat_jUVCamera_UVCWebCam
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_pl_hawat_jUVCamera_UVCWebCam_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pl_hawat_jUVCamera_UVCWebCam
 * Method:    captureFrame
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_pl_hawat_jUVCamera_UVCWebCam_captureFrame
  (JNIEnv *, jobject);


#ifdef	__cplusplus
}
#endif

#endif	/* PL_HAWAT_JUVCAMERA_UVCWEBCAM_H */

